Repository CycloneDX/cyclonedx-maven-plugin, pull requests merged in 2024-11, with the labels that each got.

#573 fixes CycloneDX/cyclonedx-maven-plugin#382
  src/main/java/org/cyclonedx/maven/DefaultModelConverter.java
  src/test/java/org/cyclonedx/maven/Issue382Test.java
  src/test/resources/issue-382/pom.xml
Labels: enhancement

#575 share isBlank(String)
  src/main/java/org/cyclonedx/maven/DefaultModelConverter.java
Labels: java

#577 simplify code
  src/main/java/org/cyclonedx/maven/BaseCycloneDxMojo.java
  src/main/java/org/cyclonedx/maven/DefaultModelConverter.java
  src/test/java/org/cyclonedx/maven/Issue521Test.java
  src/test/resources/issue-521/app/pom.xml
  src/test/resources/issue-521/lib/pom.xml
  src/test/resources/issue-521/pom.xml
Labels: enhancement

#584 upgrade github-pages-deploy-action
  .github/workflows/maven.yml
Labels: build
